name: ops

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    network_mode: none
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/healthchecks.png
    
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    hostname: SKULLSERVER
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "0 0 * * *"
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA}/watchtower/config.json:/config.json
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/watchtower.png

  znc:
    container_name: znc
    image: lscr.io/linuxserver/znc:latest
    ports:
      - 6501:6501
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APP_DATA}/znc:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: znc.${DOMAIN_NAME}
      npm.proxy.port: "6501"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/znc.png
      net.unraid.docker.webui: https://znc.${DOMAIN_NAME}

  thelounge:
    container_name: thelounge
    image: lscr.io/linuxserver/thelounge:latest
    ports:
      - 9000:9000
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APP_DATA}/thelounge:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: irc.${DOMAIN_NAME}
      npm.proxy.port: "9000"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/thelounge.png
      net.unraid.docker.webui: https://irc.${DOMAIN_NAME}
  
  obsidian-ls:
    container_name: obsidian-ls
    image: couchdb:latest
    user: ${PUID}:${PGID}
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: ${DEFAULT_APP_USERNAME}
      COUCHDB_PASSWORD: ${DEFAULT_APP_PASSWORD}
    volumes:
      - ${APP_DATA}/obsidian-ls/couchdb-data:/opt/couchdb/data
      - ${APP_DATA}/obsidian-ls/couchdb-etc:/opt/couchdb/etc/local.d
    restart: unless-stopped
    labels:
      npm.proxy.domain: obsidian-ls.${DOMAIN_NAME}
      npm.proxy.port: "5984"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/obsidian.png