name: o11y

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - "8084:8080"
    environment:
      TZ: ${TZ}
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA}/dozzle:/data
    restart: unless-stopped
    labels:
      npm.proxy.domain: logs.${DOMAIN_NAME}
      npm.proxy.port: "8084"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/dozzle.png
      net.unraid.docker.webui: https://logs.${DOMAIN_NAME}

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped
    labels:
      npm.proxy.domain: uptime-kuma.${DOMAIN_NAME}
      npm.proxy.port: "3001"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/uptime-kuma.png
      net.unraid.docker.webui: https://uptime-kuma.${DOMAIN_NAME}

  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    ports:
      - 8181:8181
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APP_DATA}/tautulli:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: tautulli.${DOMAIN_NAME}
      npm.proxy.port: "8181"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/tautulli.png
      net.unraid.docker.webui: https://tautulli.${DOMAIN_NAME}

  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    ports:
      - "8081:80"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      SPEEDTEST_SCHEDULE: 0 */2 * * *
      PRUNE_RESULTS_OLDER_THAN: 90
      TZ: ${TZ}
      APP_KEY: ${SPEEDTEST_APP_KEY}
    volumes:
      - ${APP_DATA}/speedtest-tracker:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: speedtest.${DOMAIN_NAME}
      npm.proxy.port: "8081"
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/speedtest-tracker.png
      net.unraid.docker.webui: https://speedtest.${DOMAIN_NAME}
